// Generated by https://quicktype.io

export interface MesasInterface {
    id_mesa: number;
    nombre_mesa: string;
    estado_mesa: string;
    imagen_mesa: string;
    user_created_mesa: string;
    date_created_mesa: Date;
    user_updated_mesa: string;
    date_updated_mesa: Date;
}
